apiVersion: v2
name: open5gs-gitops
description: GitOps deployment of Open5GS 5G Core
type: application
version: 0.1.0
appVersion: "2.7.5"

dependencies:
  - name: open5gs
    version: 2.2.0
    repository: oci://registry-1.docker.io/gradiant
